dnp:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/my_new_ptt?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: net.sf.log4jdbc.DriverSpy
    filters: log4j,wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:/com/dnp/test/modular/dao/impl/*Mapper.xml
  typeAliasesPackage: com.dnp.test.modular.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multiple  ResultSetsEnabled: true

server:
  servlet:
    context-path: /baomidou/
  port: 80
  tomcat:
    uri-encoding: UTF-8
